package demo;

import drools.adapter.AIOData;
import drools.adapter.AIODataParsed;

rule "humidity 优"
    when
        aioData : AIOData(humidity != null, humidity >= 20, humidity <= 80);
        aioDataParsed : AIODataParsed();
    then
        aioDataParsed.setHumidity("优");
        System.out.println("规则中打印日志：优!");
    end

rule "humidity 良"
    when
          aioData : AIOData(humidity != null,  10 <= humidity, humidity < 20 ||  80 < humidity, humidity <= 90);
          aioDataParsed : AIODataParsed();
      then
          aioDataParsed.setHumidity("良");
          System.out.println("规则中打印日志：良!");
      end

rule "humidity 差"
    when
        aioData : AIOData(humidity != null, humidity < 10 || humidity > 90);
        aioDataParsed : AIODataParsed();
    then
        aioDataParsed.setHumidity("差");
        System.out.println("规则中打印日志：差!");
    end

rule "temperature 优"
    when
        aioData : AIOData(temperature >= 16, temperature <= 28);
        aioDataParsed : AIODataParsed();
    then
        aioDataParsed.setTemperature("优");
        System.out.println("规则中打印日志：优!");
    end

rule "temperature 良"
    when
          aioData : AIOData( 4 <= temperature, temperature < 16 ||  28 < temperature, temperature <= 36);
          aioDataParsed : AIODataParsed();
      then
          aioDataParsed.setTemperature("良");
          System.out.println("规则中打印日志：良!");
      end

rule "temperature 差"
    when
        aioData : AIOData(temperature < 4 || temperature > 36);
        aioDataParsed : AIODataParsed();
    then
        aioDataParsed.setTemperature("差");
        System.out.println("规则中打印日志：差!");
    end