dev:
  host: "tcp://10.76.3.70:8883"
  username: "admin"
  password: "123456"
test:
  host: "tcp://10.76.3.66:8883"
  port: "8883"
  username: "admin"
  password: "Wm4Magp6P11xzWEdcS"
beta:
  host: "tcp://10.76.2.154:1883"
  username: "admin"
  password: "123456"
prod:
  host: "tcp://10.76.2.45:1883"
  username: "admin"
  password: "admin"

dev-down:
  host: "tcp://10.76.3.70:8883"
  username: "admin"
  password: "admin"
test-down:
  host: "tcp://10.76.3.66:8883"
  username: "admin"
  password: "Wm4Magp6P11xzWEdcS"
beta-down:
  host: "tcp://10.76.2.154:1883"
  username: "test4pipeline"
  password: "123456"
prod-down:
  host: "tcp://10.76.2.45:1883"
  username: "admin"
  password: "admin"